backend:
  name: github
  repo: madalina-taher/madelina-coffee
  branch: main
  auth_type: implicit 

local_backend: false # Khalliha false dima fel GitHub

media_folder: "public/images/menu"
public_folder: "/images/menu"

collections:
  - name: "config-menu"
    label: "☕ Menu Management"
    files:
      - label: "Madelina Coffee Shop"
        name: "menu-data"
        file: "src/data/menu.json"
        editor:
          preview: false 
        fields:
          - label: "La Carte"
            name: "plats"
            widget: "list"
            summary: '{{fields.category}} ➔ {{fields.title}} ({{fields.price}} DT)'
            add_to_top: true
            fields:
              - label: "Catégorie"
                name: "category"
                widget: "select"
                options: 
                  - { label: "☕ Café & Chaud", value: "☕ Café & Chaud" }
                  - { label: "🍰 Gâteaux", value: "🍰 Gâteaux" }
                  - { label: "🍳 Cuisine & Brunch", value: "🍳 Cuisine & Brunch" }
                  - { label: "🥤 Jus & Frais", value: "🥤 Jus & Frais" }
              
              - label: "Nom du Plat"
                name: "title"
                widget: "string"
              
              - label: "Prix (DT)"
                name: "price"
                widget: "number"
                value_type: "float"
              
              - label: "Lien de la Photo (URL)"
                name: "image"
                widget: "string" # Rod'ha string bech t'7at link ImgBB wala Cloudinary direct
                hint: "Uploadi e-taswira f'Cloudinary w 7ot el link houni bech ma takolch el bandwidth."
              
              - label: "Description"
                name: "description"
                widget: "text"
                required: false